### ISSUE TITLE
An input error when select data path

### ISSUE THREAD

**Issue by KerlKK** [ranieremenezes/easyfermi#37]
Hello,

Thank you for your tool! It has been really helpful to me. However, I am encountering a problem after upgrading to version 2.0.7.

When I input my data path and try to start, I receive an unexpected error message stating that some fields are not properly filled (as shown in the figure). However, the input paths all exist. I am currently stuck at this point.

Could you please fix these problems or provide me with some advice?

Thank you!

![2024-02-24 005510](https://github.com/ranieremenezes/easyfermi/assets/134985814/46c0aeaf-00ab-48e8-89ca-e404fe79e8ef)

**Comment by ranieremenezes** [comment]
Hello,

Do you have any error messages in the terminal?

**Comment by KerlKK** [comment]
Sorry for the late reply.

Actually, I can't find any new error message in the terminal except for an error message when the program starts (see the following figure).

![2024-02-24 201419](https://github.com/ranieremenezes/easyfermi/assets/134985814/906de247-1c9b-4882-baff-6822197996ac)

**Comment by ranieremenezes** [comment]
Ok, I see.

Could you please double-check that you have only "XXXX_PH_0X.fits" photon files in your photon directory?
I noticed that easyfermi 2.0.7 does not give an alert if it finds no PH files, so probably this is the case for you.
I already fixed that and this new feature will be available in version 2.0.8.

Let me know if this solves the problem.

**Comment by KerlKK** [comment]
Yes, I discovered that the spacecraft file was also placed in the photo directory, as I used to do in version 1.X.X. 
After moving the spacecraft out of the photo directory, the program started working.

Thanks for your help!

**Comment by ranieremenezes** [comment]
Thank you for the feedback!

**Comment by HealthyPear** [comment]
I still get this error from the latest commit on the `main` branch when starting an analysis from scratch.

**Comment by HealthyPear** [comment]
I only managed to download Diffuse data, but trying to download either of Spacecraft or Photons triggers this error.

**Comment by HealthyPear** [comment]
My use case is slightly different than this, as I am starting from scratch, but the error is the same: feel free to open a separate issue if you feel it is better!

**Comment by ranieremenezes** [comment]
Hmm, I see. In this case the problem is probably with astroquery. The diffuse emission files are downloaded directly from here: https://fermi.gsfc.nasa.gov/ssc/data/access/lat/BackgroundModels.html, while the Photon and spacecraft files are queried with astroquery. If you see a "404 error" in the terminal, this means that astroquery could not reach the Fermi-LAT server. There are two ways to proceed in this case:
1) Wait a couple of hours and try again.
2) Download the files manually as shown in the YouTube tutorials.

**Comment by HealthyPear** [comment]
Is this warning related?

> /Users/michele/Applications/miniforge3/envs/easyfermi/lib/python3.9/site-packages/astroquery/fermi/__init__.py:37: UserWarning: Experimental: Fermi-LAT has not yet been refactored to have its API match the rest of astroquery.
>   warnings.warn("Experimental: Fermi-LAT has not yet been refactored to have "

**Comment by ranieremenezes** [comment]
This warning is not a problem. Do you see the Photon and spacecraft files in the ./Photon and ./spacecraft directories? In v2.0.8 easyfermi prints a warning in the log if it does not find the Photon files.

**Comment by HealthyPear** [comment]
I am starting from scratch, so I am starting from an empty directory (apart from the `Diffuse` sub-directory that I managed to download)

**Comment by HealthyPear** [comment]
Tried again this morning with the same result, unfortunately.

Can you replicate this issue yourself?

**Comment by ranieremenezes** [comment]
Problem solved. Can you try again with vesion 2.0.9?

**Comment by HealthyPear** [comment]
Now it works again
